title: DarkShadow Blog
description: CTF | Networking | Cyber Skills

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sass-converter

sass:
  sass_dir: assets/css
  style: compressed

header_pages:
  - index.md
  - about.md
