title: darkShadow Tech Blog
description: CTF | Networking | Cyber Skills
author: Ashura

sass:
  style: compressed

theme: minima

# Dark hacker styling
minima:
  skin: dark

header_pages:
  - index.md
  - about.md
